name: interesting_places
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^5.0.0
  geolocator: ^10.0.1
  get_it: ^7.6.4
  image_picker: ^1.0.4
  injectable: ^2.3.0
  latlong2: ^0.9.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
